name: vivo
channels:
    - conda-forge
    - pytorch
dependencies:
    - black
    - pip
    - python=3.7
    - pytorch=1.4
    - spacy
    - torchtext
    - tqdm
    - pip:
        - sacrebleu
        - sentencepiece
